### ISSUE TITLE
NoSuchElementException below LaunchCommandHandler.execute (thrown in AbstractList$Itr.next)

### ISSUE THREAD

**Issue by codetrails** [codetrails/ctrlflow-aer-demo#1]
The following problem was reported via _Ctrlflow Automated Error Reporting_:

**Message:** null

```
java.util.NoSuchElementException: null
    at java.util.AbstractList$Itr.next(AbstractList.java:364)
    at com.ctrlflow.aer.demo.ui.LaunchCommandHandler.execute(LaunchCommandHandler.java:23)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-1)
    at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
    at java.lang.reflect.Method.invoke(null:-1)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
```

The reporter(s) left the following **comment(s):**

_Jane Doe_ wrote on incident 0002:

> This problem occurs whenever I start the plug-in in a workspace _without_ projects.

**Bundles:**

| Name | min | max |
| --- | --- | --- |
| com.ctrlflow.aer.demo | 1.0.0.v20150107-0800 | 1.0.0.v20150107-0800 |
| org.eclipse.e4.core.di | 1.5.0.v20150421-2214 | 1.5.0.v20150421-2214 |
| org.eclipse.ui | 3.107.0.v20150507-1945 | 3.107.0.v20150507-1945 |

**Operating Systems:**

| Name | min | max |
| --- | --- | --- |
| Mac OS X | 10.10.5 | 10.10.5 |

---

The above information is a snapshot of the collected data. Visit http://demo.ctrlflow.com/reviewers/#!/problems/000000000000000000020000 for the latest data.

Your friendly _Ctrlflow Automated Error Reporting_ bot

**Comment by codetrails** [comment]
This has been fixed in **version 2.0.0**.
